# This is a basic workflow to help you get started with Actions
variables:
  DATABASE_URL: mysql://root:toor@127.0.0.1:3306/lesson?
  DB_PASSWORD: toor
  DB_DATABASE: lesson
  DB_USERNAME: root
  
name: Back CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Installation Docker
        run: |
          cd Back
          docker-compose build
          docker-compose up -d
      - name: Install composer dependencies
        run: |
          cd Back
          docker-compose exec -T app bash
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Migration
        run: |
          cd Back
          docker-compose exec -T app bash
          php bin/console doctrine:migration:migrate
      - name: Doctrine
        run: |
          cd Back
          docker-compose exec -T app bash
          php bin/console doctrine:fixtures:load
      - name: Lancement des test
        run: |
          cd Back
          docker-compose exec -T app bash
          php bin/phpunit
