# This is a basic workflow to help you get started with Actions

name: Cypress CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name : Lancement du Back
        run : |
          cd Back
          docker-compose build
          docker-compose up -d
          docker-compose exec -T app bash
          composer install
          php bin/console doctrine:migrations:migrate
          php bin/console doctrine:fixtures:load --no-interaction
      - name: Installation des dépendances
        run: |
          cd Front
          npm ci
      - name: Lancement test Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: Front
          start: npm start
    
